name: filmes_dbc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/tlou2.jpg
  - assets/Central_do_Brasil.jpg
  - assets/o_show_de_truman.jpg
  - assets/Oppenheimer.jpg
